// @ts-check
/**
 * The shared ESLint base for every CoolMS frontend package.
 *
 * Framework-agnostic on purpose: only TypeScript and general-quality rules live
 * here, so a React package would inherit the same
 * `strict-boolean-expressions`, `no-floating-promises` and
 * `prefer-nullish-coalescing` bar the Angular ones run today. One bar, many
 * consumers — that is the whole point, and it is worth nothing if a copy
 * quietly says something else.
 *
 * **Why a factory, not a static config.** The canonical copy sits in
 * `packages/`, outside any `node_modules/` tree, so bare-import resolution
 * would fail at load time. The consumer passes its own `typescript-eslint` and
 * `globals` in; this file provides the rule shape.
 *
 * **This file is VENDORED, not imported across package boundaries.** Every
 * package that uses it holds a byte-identical copy beside its own
 * `eslint.config.mjs`, because a package must be able to lint inside its own
 * repository, where `packages/eslint.config.base.mjs` does not exist. The
 * copies are generated by `tools/sync-eslint-base.mjs` and verified by
 * `tools/check-eslint-base-drift.mjs`, which `make check-fe` runs.
 *
 * So: edit THIS file, then run the sync. A copy edited in place is reverted by
 * the next sync without a word.
 *
 * **Strictness tier**: `recommended-type-checked` everywhere. Each consumer's
 * own config tightens or relaxes per directory — a package close to vendored
 * code turns the `no-unsafe-*` family off, because those rules would report the
 * library rather than the package.
 *
 * **Build-gate policy**: errors fail the build, warnings do not. A strict rule
 * that surfaces fifty violations should become visible without blocking the
 * change that revealed it; tightening is its own pass.
 *
 * @param {{ tseslint: import('typescript-eslint').Config, globals: any }} deps
 * @returns {import('typescript-eslint').ConfigArray}
 */
export default function createBaseConfig({ tseslint, globals }) {
    return tseslint.config(
        // Ignore generated output across every consumer that spreads this base.
        {
            ignores: [
                '**/dist/**',
                '**/node_modules/**',
                '**/coverage/**',
                '**/.angular/**',
                '**/public/**', // admin SPA build output goes here
            ],
        },

        // Base TS recommendation: type-checked rules, scoped to TS files
        // only. The consumer's languageOptions.parserOptions.project must
        // point at its tsconfig for these to fire (we set that in each
        // consumer config). Scoping to `**/*.ts` (and friends) keeps
        // template / HTML files out of the TS rule blast radius — Angular
        // inline-template extractions otherwise trip rules like
        // `ban-ts-comment` that expect a TS AST.
        ...tseslint.configs.recommendedTypeChecked.map((c) => ({
            ...c,
            files: c.files ?? ['**/*.{ts,mts,cts}'],
        })),

        {
            files: ['**/*.{ts,mts,cts,js,mjs,cjs}'],
            languageOptions: {
                globals: {
                    ...globals.browser,
                    ...globals.node, // tooling files (this config, build scripts)
                },
            },
            rules: {
                // ----- TS quality rules layered on top of recommendedTypeChecked -----
                // These specifically target patterns we see across the admin SPA today
                // + want gone from the future `theme-angular` UI kit:

                '@typescript-eslint/no-floating-promises': 'error',
                // Catches Observable -> Promise interop slip-ups: an unawaited
                // `firstValueFrom(...)` that should have been thenned. Real bug
                // pattern; cheap to fix.

                '@typescript-eslint/no-misused-promises': 'error',
                // `<button (click)="async() => ...">` style mistakes where a
                // Promise is passed where void is expected. Common Angular bug.

                '@typescript-eslint/prefer-nullish-coalescing': 'error',
                // Force `??` over `||` for nullable defaults. Avoids the
                // `'' || 'fallback'` -> `'fallback'` footgun on empty strings.

                '@typescript-eslint/no-unnecessary-condition': 'warn',
                // Downgrade to warn for the first pass — type-narrowing across
                // signals + RxJS can confuse the rule into false positives.
                // Cleanup ship can promote to error once those are addressed.

                // ----- Consistency rules -----

                '@typescript-eslint/consistent-type-imports': [
                    'error',
                    { fixStyle: 'inline-type-imports' },
                ],
                // `import { type Foo } from './x'` style — keeps the TS type
                // graph clean across modules, helps with tree-shaking.

                '@typescript-eslint/no-unused-vars': [
                    'warn',
                    {
                        argsIgnorePattern: '^_',
                        varsIgnorePattern: '^_',
                        caughtErrorsIgnorePattern: '^_',
                    },
                ],

                // ----- Pervasive-pattern downgrades -----
                // These would surface hundreds of violations on the existing
                // codebase. Warn now; promote to error after the per-directory
                // cleanups land.

                '@typescript-eslint/no-explicit-any': 'warn',
                '@typescript-eslint/no-unsafe-assignment': 'warn',
                '@typescript-eslint/no-unsafe-member-access': 'warn',
                '@typescript-eslint/no-unsafe-call': 'warn',
                '@typescript-eslint/no-unsafe-argument': 'warn',
                '@typescript-eslint/no-unsafe-return': 'warn',
                // The five `no-unsafe-*` rules trip whenever an HTTP response
                // isn't typed at the boundary. Plenty of those today —
                // documented as a known cleanup, deliberately not blocking.
            },
        },

        // Tooling files (config, scripts) shouldn't require a tsconfig project
        // entry to be linted. Disable type-checked rules for these.
        {
            files: ['**/*.{js,mjs,cjs}', '**/eslint.config.{js,mjs,cjs}'],
            ...tseslint.configs.disableTypeChecked,
        },
    );
}
